apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-postgres-pvc
  namespace: seva
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-postgres
  namespace: seva
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-postgres
  template:
    metadata:
      labels:
        app: auth-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          env:
            - name: POSTGRES_USER
              value: "seva"
            - name: POSTGRES_PASSWORD
              value: "seva"
            - name: POSTGRES_DB
              value: "auth_db"
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: auth-postgres-data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "seva", "-d", "auth_db"]
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: auth-postgres-data
          persistentVolumeClaim:
            claimName: auth-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: auth-postgres
  namespace: seva
spec:
  selector:
    app: auth-postgres
  ports:
    - port: 5432
      targetPort: 5432